# Generated by Django 3.0.8 on 2020-08-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.TextField(max_length=255)),
                ('head', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('count_view', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='pic/')),
                ('tag', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.Tag')),
            ],
        ),
    ]
