# Generated by Django 3.0.8 on 2020-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='name',
            new_name='head',
        ),
        migrations.AddField(
            model_name='sticker',
            name='count_view',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='sticker',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='price',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sticker',
            name='tag',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
