# Generated by Django 3.0.8 on 2020-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200720_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='sticker',
            name='count_view',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='tag',
        ),
        migrations.AddField(
            model_name='sticker',
            name='tag',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
