# Generated by Django 3.0.8 on 2020-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200720_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='tag',
        ),
        migrations.AddField(
            model_name='sticker',
            name='tag',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
