"""empty message

Revision ID: 3437ddf66dba
Revises: 3f5f7053ab5c
Create Date: 2020-08-03 00:12:45.272655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3437ddf66dba'
down_revision = '3f5f7053ab5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
