"""empty message

Revision ID: adf72d2b2966
Revises: 3437ddf66dba
Create Date: 2020-08-03 00:15:13.912836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf72d2b2966'
down_revision = '3437ddf66dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
