version: '3.7'
services:
  goods_service:
    container_name: goods_service
    hostname: goods_service
    build: goods/
    command: bash -c "pip install -r ./goods/requirements.txt &&
                      python ./goods/manage.py migrate &&
                      python ./goods/manage.py loaddata initial_data.json &&
                      python ./goods/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/ #for unix
     # - /home/docker/projects/:/code/ # for win7 with custom shared folder
    depends_on:
      - db
  db:
    container_name: goods_db
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/


  db_user_service:
    container_name: user_db
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  redis_db:
    container_name: redis_db
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_HOST: redis_db
    ports:
      - "6379:6379"

  user_service:
    container_name: user_service
    build: user_service/
    command: bash -c "
      cd user_service &&
      alembic upgrade head &&
      python main.py"
    volumes:
      - .:/user_service_code/ #for unix
     # - /home/docker/projects/:/user_service_code/ # for win7 with custom shared folder

    depends_on:
      - db_user_service
      - redis_db

  email_service:
    container_name: email_service
    build: email_service/

    command: bash -c "python -m venv /env && . /env/bin/activate &&
      cd email_service &&
      poetry install &&
      /env/bin/alembic upgrade head &&
      /env/bin/uvicorn --host 0.0.0.0 --port 8081 email_service.asgi:app --reload"

    volumes:
       - .:/email_service_code/ #for unix
       #- /home/docker/projects/:/src/ # for win7 with custom shared folder


    depends_on:
      - db_user_service


  db_email_service:
    container_name: db_email_service
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  rabbit:
    rabbit:
      container_name: rabbit
      build: rabbit_auto_queues
      hostname: rabbit
      ports:
        - "15672:15672"
        - "5672:5672"

  mon_service:
    container_name: mon_service
    build: mon/

    command: bash start.sh #"celery worker -P celery_pool_asyncio:TaskPool -A mon.cel.tasks"

    volumes:
      - .:/email_service_code/ #for unix
    # - /home/docker/projects/mon/:/mon_code/ # for win7 with custom shared folder

    depends_on:
      - db_user_service

  db_mon_service:
    container_name: db_mon_service
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/
  api:
    container_name: api
    build: api/

    command: bash -c "poetry install && poetry run uvicorn api_app.asgi:app --reload --host 0.0.0.0 --port 8083"

    volumes:
      - .:/api/ #for unix
      #- /home/docker/projects/api/:/api/ # for win7 with custom shared folder

    ports:
      - 8083:8083
    depends_on:
      - db_user_service
  api_redis:
    container_name: api_redis
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_HOST: redis_db
    ports:
      - "6380:6379"