version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  web_service:
    build: goods/
    command: bash -c "pip install -r ./goods/requirements.txt &&
                      python ./goods/manage.py migrate &&
                      python ./goods/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code/

    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  stickers: