version: '3.7'
services:
  db:
    container_name: goods_db
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  goods_service:
    container_name: goods_service
    build: goods/
    command: bash -c "pip install -r ./goods/requirements.txt &&
                      python ./goods/manage.py migrate &&
                      python ./goods/manage.py loaddata initial_data.json &&
                      python ./goods/manage.py runserver 0.0.0.0:8000"

    volumes:
    #  - .:/code/ #for unix
      - /home/docker/projects/:/code/ # for win7 with custom shared folder

    ports:
      - 8000:8000
    depends_on:
      - db

  db_user_service:
    container_name: user_db
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  redis_db:
    container_name: redis_db
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_HOST: redis_db
    ports:
      - "6379:6379"

  user_service:
    container_name: user_service
    build: user_service/
    command: bash -c "
      cd user_service &&
      alembic upgrade head &&
      python main.py"

    volumes:
      - .:/user_service_code/ #for unix
    #  - /home/docker/projects/:/user_service_code/ # for win7 with custom shared folder

    ports:
      - 8080:8080
    depends_on:
      - db_user_service
      - redis_db

  email_service:
    container_name: email_service
    build: email_service/

    command: bash -c "python -m venv /env && . /env/bin/activate &&
      cd email_service &&
      poetry install &&
      /env/bin/alembic upgrade head &&
      /env/bin/uvicorn --host 0.0.0.0 --port 8081 email_service.asgi:app --reload"

    volumes:
    #  - .:/email_service_code/ #for unix
      - /home/docker/projects/:/src/ # for win7 with custom shared folder

    ports:
      - 8081:8081
    depends_on:
      - db_user_service


  db_email_service:
    container_name: db_email_service
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/

  rabbit:
    container_name: rabbit
    image: "rabbitmq:3-management"
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "TESTVOLUME"
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "test"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
  mon_service:
    container_name: mon_service
    build: mon_service/

    command: bash -c "python -m venv /env && . /env/bin/activate &&
      cd email_service &&
      poetry install &&
      /env/bin/alembic upgrade head &&
      /env/bin/uvicorn --host 0.0.0.0 --port 8081 email_service.asgi:app --reload"

    volumes:
      #  - .:/email_service_code/ #for unix
      - /home/docker/projects/:/src/ # for win7 with custom shared folder

    ports:
      - 8081:8081
    depends_on:
      - db_user_service

  db_mon_service:
    container_name: db_mon_service
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data/