"""empty message

Revision ID: 1bde52e51cda
Revises: 
Create Date: 2020-08-13 10:49:31.690575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bde52e51cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('service', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.Column('status', sa.Unicode(), nullable=True),
    sa.Column('req_time', sa.Unicode(), nullable=True),
    sa.Column('res_time', sa.Unicode(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
