FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN pip install poetry==1.0.10
RUN poetry config virtualenvs.create false

RUN mkdir /src/
WORKDIR /src
#COPY poetry.lock pyproject.toml /src/


#RUN python -m venv /env && . /env/bin/activate && poetry install

#RUN poetry install




